from typing import Dict, Sequence, Set, Tuple, Optional

Point = Tuple[int, int]
Vector = Tuple[int, int]

class TranslationalEquivalence:
    pattern: Sequence[Point]
    translators: Set[Vector]
    sub_tecs: Sequence[TranslationalEquivalence]

    def __init__(self, pattern: Sequence[Point], translators: Set[Vector], sub_tecs: Optional[Sequence[TranslationalEquivalence]] = ...) -> None: ...
    @property
    def coverage(self) -> Set[Point]: ...
    @property
    def compression_ratio(self) -> float: ...
    def compactness(self, points: Set[Point]) -> float: ...
    def __repr__(self) -> str: ...
    def summary(self, indent: int = 0) -> str: ...

def find_mtps(dataset: Sequence[Point], restrict_dpitch_zero: bool = ...) -> Dict[Vector, Sequence[Point]]: ...
def build_tecs_from_mtps(dataset: Sequence[Point], restrict_dpitch_zero: bool = ...) -> Sequence[TranslationalEquivalence]: ...
def cosiatec_compress(dataset: Sequence[Point], restrict_dpitch_zero: bool = ...) -> Sequence[TranslationalEquivalence]: ...
def recursive_cosiatec_compress(dataset: Sequence[Point], restrict_dpitch_zero: bool = ..., min_pattern_size: int = ...) -> Sequence[TranslationalEquivalence]: ...